# SCREEN DIMENTIONS & GENERAL DISPLAY CONFIG
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 3

# PLAYER CONFIG
PLAYER_RADIUS = 20
PLAYER_MAX_ROTATION_SPEED = 300
PLAYER_ROTATIONAL_ACCELERATION = 500
PLAYER_ROTATIONAL_DRAG_DECELEARTION_COEFFICIENT = 0.997
PLAYER_MAX_SPEED = 700
PLAYER_LINEAR_ACCELERATION = 250
PLAYER_LINEAR_DRAG_DECELERATION_COEFFICIENT = 0.997
PLAYER_LIVES = 3

# ASTEROID CONFIG
ASTEROID_MIN_RADIUS = 20
ASTEROID_SIZES = 3 
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_SIZES
ASTEROID_AVG_VERTICES = 15
ASTEROID_VERTICES_SIGMA = 1
ASTEROID_MAX_ROTATION_SPEED = 100

# SHIELD POWERUP CONFIG
SHIELD_POWERUP_GENERAL_SPAWN_RATE_SECONDS = 25
SHIELD_POWERUP_ACTIVE_TIME_SECONDS = 15
SHIELD_RADIUS = 70

# SPEED POWERUP CONFIG
SPEED_POWERUP_GENERAL_SPAWN_RATE_SECONDS = 30
SPEED_POWERUP_ACTIVE_TIME_SECONDS = 15

# AUTOCANNON CONFIG
AUTOCANNON_MAGAZINE_CAPACITY = 350
AUTOCANNON_RELOAD_TIME_SECONDS = 30
AUTOCANNON_PROJECTILE_RADIUS = 5 
AUTOCANNON_PROJECTILE_SPEED = 700

# SHOTGUN CONFIG
SHOTGUN_MAGAZINE_CAPACITY = 5
SHOTGUN_PELLETS_PER_SHOT = 100
SHOTGUN_RELOAD_TIME_SECONDS = 60
SHOTGUN_PROJECTILE_RADIUS = 2
SHOTGUN_PROJECTILE_SPEED = 250
SHOTGUN_COOLDOWN_TIME_SECONDS = 1.1

# BOMB CONFIG
BOMB_MAGAZINE_CAPACITY = 1
BOMB_RELOAD_TIME_SECONDS = 60
BOMB_RADIUS = 15 
BOMB_COOLDOWN_TIME_SECONDS = 1.5
BOMB_FRAGMENTS_AVG = 600
BOMB_FRAGMENTS_DIST_SIGMA = 100
BOMB_FRAGMENT_RADIUS = 1
BOMB_FRAGMENT_SPEED = 900
